name: Publish web api
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  publish:
    env:
      APP-NAME: ${{ secrets.AZURE_WEBAPP_NAME }}
      PACKAGE_PATH: ${{ secrets.AZURE_PACKAGE_PATH }}
    runs-on: ubuntu-latest
    steps:
      - name: fetch code from repository
        uses: actions/checkout@v5

      - name: setupt .net environment
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '8.0.x'
          
      - name: restore project
        run: dotnet restore ./CliniqueBackend.sln
      - name: build project
        run: dotnet build ./CliniqueBackend.sln --configuration Release --no-restore

      - name: publish project
        run: dotnet publish ./CliniqueBackend.sln --configuration Release --no-build --output ${{ env.PACKAGE_PATH }}

      - name: deployment
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.APP_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: ${{ env.PACKAGE_PATH }}